bruin-data/bruin

- .github/workflows/build-test.yml
- .github/workflows/release.yml
- .goreleaser.yaml
- Migrate goreleaser from v1 to v2
- Skip windows ARM build from goreleaser
> Migrate goreleaser from v1 to v2 

- cmd/fetch.go
- main.go
This PR adds the fetch query command to execute SQL queries on specified connections with optional JSON or table-formatted output.
`bruin fetch query --connection <connection-name> --query "<SQL-query>" --output <output-format>`
> Fetch command

- cmd/run.go
- pkg/lint/lint.go
- pkg/lint/list.go
- pkg/lint/query.go
- pkg/lint/rules.go
Pipeline
```
yuvraj@Yuvrajs-MacBook-Pro ~/W/b/bruin (bru-321) [1]> go run main.go run  ./examples/simple-pipeline/
Pipeline: bruin-init (.)
└── Invalid cron schedule 'dailyadds' (valid-pipeline-schedule)
destinations (assets/athena.sql)
└── Asset name 'destinations' is not unique, please make sure all the task names are unique (task-name-unique)
├─ /Users/yuvraj/Workspace/bruin-data/bruin/examples/simple-pipeline/assets/athena.sql
└─ /Users/yuvraj/Workspace/bruin-data/bruin/examples/simple-pipeline/assets/duckdb.sql
✘ Checked 1 pipeline and found 2 issues, please check above.
exit status 1
```
Single Assets 
```
yuvraj@Yuvrajs-MacBook-Pro ~/W/b/bruin (bru-321) [1]> go run main.go run  ../test/bruin-pipeline/assets/example.sql 
Pipeline: bruin-init (.)
└── The pipeline has a cycle with …
```
> Added validation for single assets in run command

- pkg/lint/list.go
- pkg/lint/rules.go
Fix: https://linear.app/bruin/issue/BRU-506/warn-if-there-is-no-assets-folder-in-validation
Test:
```
yuvraj@Yuvrajs-MacBook-Pro ~/W/b/bruin (bru-506)> go run main.go validate  ./examples/simple-pipeline/                                               (bruin) 
Validating pipelines in './examples/simple-pipeline/' for 'default' environment...
Pipeline: bruin-init (.)
└── Invalid cron schedule 'dailyadds' (valid-pipeline-schedule)
(/Users/yuvraj/Workspace/bruin-data/bruin/examples/simple-pipeline)
└── Assets directory does not exist at '/Users/yuvraj/Workspace/bruin-data/bruin/examples/simple-pipeline/assets' (assets-directory-exist)
✘ Checked 1 pipeline and found 1 issue and 1 warning, please check above.
An error occurred: validation failed
exit status 1
```
> Added validation rule for checking assets dir as warning 

- .goreleaser.yaml
- pkg/connection/connection.go
- pkg/connection/helper.go
- pkg/connection/helper_test.go
When user have correct config.
```
yuvraj@Yuvrajs-MacBook-Pro ~/W/b/bruin (revert-bgconnection)> go run main.go validate  ../bruin-dev/                                                                      (bruin) 
Validating pipelines in '../bruin-dev/' for 'default' environment...
Pipeline: bruin-init (bruin-pipeline)
myschema.example (assets/example.sql)
└── Invalid query found at index 0: googleapi: Error 403: Access Denied: Project name-of-the-project: User does not have bigquery.jobs.create permission in project name-of-the-project., accessDenied (bigquery-validator)
├─ The failing query is as follows:
└─ CREATE OR REPLACE TABLE myschema.example   AS
SELECT 1 as id, 'Spain' as country , 'Juan' as name
union all
SELECT 2 as id, 'Germany' as country , 'Markus' as name
union all
SELECT …
```
> Revert Big Query connection validation logic

- cmd/run.go
- pkg/config/manager.go
- pkg/config/manager_test.go
- pkg/snowflake/checks_test.go
- pkg/snowflake/db_test.go
before `bruin run` validate all connections necessary are present to avoid lots of errors on big pipelines
> Validate connections before running

- .golangci.yml
- pkg/config/connections.go
- pkg/duckdb/db.go
- pkg/duckdb/ephemeral_db.go
- pkg/duckdb/lock.go
- pkg/duckdb/lock_test.go
- pkg/lint/print.go
- pkg/pipeline/pipeline.go
At the moment CLI locks the DB as soon as it instantiates the connection and it unlocks it on exit. This means that if for example, we had a python asset that was also trying to access that same db it won't be able to since CLI is blocking anything else from writing. 
We only need to lock the DB for the time it takes to run queries (select or update)
Only lock DB when sending SQL to the connections, and unlock right after. This could be achieved by wrapping the current duckdb connection
> Use ephemeral duck connection

- cmd/init.go
This PR adds the functionality to initialize a Git repo if there's not one already. effectively, it assumes that either the user is in an existing git repo, or it'll create on in the template path as well.
> feature: make init smart enough to create a git repo if needed

- cmd/helpers.go
- cmd/render.go
Test
```
❯ go run main.go render -o json  templates/duckdb/assets/non-asset.py                                                                                                                               (base) 
{"error":"no asset found"}
exit status 1
```
> fix panic in render command

- cmd/internal.go
- cmd/internal_test.go
- pkg/sqlparser/parser_test.go
Asset1 
```
/* @bruin
name: example
type: duckdb.sql
materialization:
type: table
depends:
- example2
@bruin */
select * from example2;
```
Asset2
```
/* @bruin
name: example2
type: duckdb.sql
materialization:
type: table
columns:
- name: id
type: integer
description: "Just a number"
primary_key: true
checks:
- name: not_null
- name: positive
- name: non_negative
- name: country
type: varchar
description: "the country"
primary_key: true
checks:
- name: not_null
- name: name
type: varchar
update_on_merge: true
description: "Just a name"
checks:
- name: unique
- name: not_null
@bruin */
select id,name, country from example2;
```
Test
```
bruin internal parse-asset example.sql
```
Output: https://jsonblob.com/1306646592982212608
> Add new flag for column lineage

- main.go
Test
```
❯ go run main.go er                                                                                                                       (base) 
No help topic for 'er'
exit status 3
~/Workspace/bruin on  help-command ?! 3s 
❯ go run main.go                                                                                                                          (base) 
NAME:
bruin - The CLI used for managing Bruin-powered data pipelines
USAGE:
bruin [global options] command [command options] 
VERSION:
dev
COMMANDS:
validate      validate the bruin pipeline configuration for all the pipelines in a given directory
run           run a Bruin pipeline
render        render a single Bruin SQL asset
lineage       dump the lineage for a given asset
clean         clean the temporary …
```
> Help command

- pkg/pipeline/lineage.go
To append the upstream column in the asset, we noticed an issue where the table name was defined in lowercase by the user, but the lineage system returned it in uppercase. This caused mismatches. To resolve this, we switched to using strings.EqualFold for case-insensitive comparison.
> Hotfix column lineage merge

- cmd/version.go
**Summary**
Adds a default http timeout when version command is called. Also adds a `--timeout` flag to version command to override this default.
If the http request fails or times out, the version information is shown as:
```
Current: dev ()
Latest: <unknown: error fetching version information>
```
`--debug` flag can be used to obtain more information about why the request failed
> cmd: version: add timeout for fetching version information

- cmd/internal.go
- pkg/pipeline/lineage.go
- pkg/pipeline/lineage_test.go
- Updated `NewLineageExtractor` to only accept sqlparser.
- Modified `TableSchema` and `ColumnLineage` methods to take the pipeline as a parameter
> Refactor lineage extraction for stateless

- cmd/run.go
- pkg/scheduler/scheduler.go
Bug scenario:
I have a pipeline like that: a -> b -> c -> d
I run only asset b: bruin run pipeline/assets/b.py
task fails
Log message:
These assets couldn't run since their parent has failed
c ,d 
-----------------------------------------------------
This error happens because we are marking the downstream of the failed Task as -> Upstreamfailed  even if we are not going to run them ( for example can happen when we are running a single asset or running specific assets with --tag without the downstream)
> downstream Log bug

- pkg/pipeline/pipeline.go
When we have a dummy.yml file in our pipeline that doesn't end with asset.yml we should ignore it
>  fix:irrelevant yml files  breaks pipeline execution

- pkg/pipeline/lineage.go
```
❯ hyperfine 'bruin internal parse-pipeline -c ./pace-export/'                                                                                                                                    Benchmark 1: bruin internal parse-pipeline -c ./pace-export/
Time (mean ± σ):      1.636 s ±  0.206 s    [User: 1.508 s, System: 0.070 s]
Range (min … max):    1.339 s …  1.912 s    10 runs
```
```
❯ hyperfine 'bruin internal parse-asset -c ./pace-export/tasks/dashboard/example.sql'                                                                                                  
Benchmark 1: bruin internal parse-asset -c ./pace-export/tasks/dashboard/ai_conversations.sql
Time (mean ± σ):     673.6 ms ± 143.4 ms    [User: 62.7 ms, System: 35.9 ms]
Range (min … max):   461.1 ms … 853.3 ms    10 …
```
> Speedup Lineage Extraction 

- pkg/lint/list.go
- pkg/lint/rules.go
- Introduced a new validation rule for detecting duplicate column checks within a single column and check if custom check have query or not
- Implemented the `ValidateDuplicateColumnChecks` and `ValidateCustomCheckQueryExists` function
- Updated the rules list in `list.go` to include the new rule with critical severity.
> Add validation rule

- pkg/bigquery/db.go
- pkg/bigquery/operator.go
when a table doesn't exist, it shouldn't try to fetch its metadata and try to compare the clustering specs with the given asset
> Bq handle error 

- pkg/bigquery/checks_test.go
- pkg/bigquery/db.go
- pkg/bigquery/db_test.go
- pkg/bigquery/operator.go
Handles materialization type changes when full-refresh flag  is given
Example Case : User has an bq.sql asset with materialization type table and wants to change it to view
> Handle materialization type changes

- cmd/connections.go
- docs/commands/connections.md
changes made : 
- made environment flag optional  --> uses the default env if the flag isn't passed 
-  deleted the  type flag --> realized this was only used for error messages creates a worst user experience
> Refactor connections test

- pkg/lint/rules.go
- pkg/lint/rules_test.go
if there's a materialization rule for the asset:
if there's incremental_key, the strategy for that materialization must be delete+insert
if there's delete+insert there must be incremental_key
> added validation for incremental keys

- pkg/pipeline/lineage.go
- pythonsrc/parser/main.py
- Bug fix for column lineage in snowflake
> hotfix: improve column lineage handling and table name extraction

- docs/platforms/clickhouse.md
- integration-tests/expected_connections_schema.json
- pkg/clickhouse/config.go
- pkg/config/connections.go
- pkg/config/manager_test.go
- pkg/config/testdata/simple.yml
- pkg/config/testdata/simple_win.yml
- pkg/connection/connection.go
- pkg/python/uv.go
Following changes are made in this PR:
- Improved connection handling by allowing users to specify secure or non-secure connections using the secure parameter
- By default, the secure parameter is set to 1, i.e secure connection.
> ClickHouse: Add Support for Secure Connection

- pkg/pipeline/lineage.go
- pkg/pipeline/lineage_test.go
- pythonsrc/parser/main_test.py
Fix: https://linear.app/bruin/issue/BRU-1557/column-lineage-bug
> Hotfix: fixed column name for query where column name used `as`

- cmd/fetch.go
- pkg/pipeline/pipeline.go
Three new flags added  :**limit** --> to limit the rows returned 
**asset** --> asset where we get the query from
**env** --> env the asset is being used on
Previously we only had the option to use **connection** and **query** flags now we can either use these two in tandem or just pass the  **asset**  if its in the default environment or combine with the **env** if the asset is not used in the default environment.  This second option detects the connection that the asset needs and unmaterializes  the query from the asset and then runs the query
> Refactor query cmd

- cmd/internal.go
- pkg/pipeline/pipeline.go
This PR changes the internal `parse-asset` command to avoid reading the full pipeline when not needed. This change itself causes ~12x speedup in a pipeline with ~1k assets on my macbook.
> do not parse the whole pipeline for asset parsing

- pkg/python/local.go
example:
```
$ bruin --debug run ./chess
2025-03-10T23:23:07.471+0530    DEBUG   cmd/run.go:486  given start date: 2025-03-09 00:00:00 +0000 UTC
2025-03-10T23:23:07.471+0530    DEBUG   cmd/run.go:496  given end date: 2025-03-09 23:59:59.999999 +0000 UTC
Analyzed the pipeline 'chess_duckdb' with 3 assets.
Pipeline: chess_duckdb (.)
No issues found
✓ Successfully validated 3 assets across 1 pipeline, all good.
Starting the pipeline execution...
2025-03-10T23:23:07.479+0530    DEBUG   scheduler/scheduler.go:615      started the scheduler loop
[2025-03-10 23:23:07] Starting: chess_playground.profiles
[2025-03-10 23:23:07] Starting: chess_playground.games
2025-03-10T23:23:07.483+0530    DEBUG   python/local.go:96      /home/user/.bruin/uv tool install --force --quiet --python 3.11 …
```
> run: log subprocess cmdline when --debug is set

- cmd/run.go
- cmd/run_test.go
This PR updates the filtering logic : 
It rolls back the following  features:
1. Existent logic :  combining --downstream and  --tags flags  while running the whole pipeline   -->  this would run the assets that has the specified tag and their downstream 
2. combining --downstream and  --exclude tag while running the whole pipeline  -->  this would  exclude  the assets that has the specified tag and also exclude  their downstream  .
And it ADDs the new logic:
1.  downstream flag can only be used if you are running a single asset (not the pipeline)
2.  Downstream flag can be combined with  --exclude-tags  flag   --> this runs  the asset and the downstream but excludes the assets that have that tag
> Update filtering logic 

- cmd/run.go
This PR removes the validation in the `bruin run` command if the user is running a single asset.
> skip validation for single assets

- pkg/emr_serverless/operator.go
- pkg/emr_serverless/retry.go
- pkg/emr_serverless/retry_test.go
* increases polling interval to 3 seconds for `ListJobRunAttempts`
* When rate limits are hit, doesn't treat it as a fatal error and continues polling.
* misc: handle pagination token
> emr_serverless: increase polling frequency + non-fatal rate limit

- go.mod
- pkg/emr_serverless/logs.go
- pkg/emr_serverless/operator.go
- pkg/lint/rules.go
This change adds support for spark driver log streaming.
Currently, only streaming of s3 logs is supported. The log location can be specified either globally once in the application configuration, or can specified as a part of the asset definition, like so:
``` yaml
name: spark_job
type: emr_serverless.spark
parameters:
entrypoint: s3://org-bucket/jobs/spark/script.py
logs: s3://org-bucket/logs/
application_id: emr_app_123
```
Both stdout and stderr are streamed.
> emr_serverless: add support for spark logs

- docs/platforms/emr_serverless.md
- pkg/emr_serverless/logs.go
- pkg/emr_serverless/operator.go
This change updates `emr_serverless.spark` assets to stream spark executor logs. No configuration changes are necessary in order to enable this feature.
> emr_serverless.spark: add support for executor logs

- cmd/lint.go
- docs/getting-started/policies.md
- integration-tests/policy.yml
- pkg/lint/policy.go
- pkg/lint/policy_builtins.go
- pkg/lint/policy_test.go
This change adds a `target` to rule definitions. This can be used to control at what level of the job hierachy the rule applies.
Valid values: `asset` or `pipeline`. If the key is omitted, it defaults to `asset`.
**Example**
```yaml
custom_rules:
- name: pipline-must-have-prefix-acme
description: Pipeline names must start with the prefix 'acme'
criteria: pipeline.Name startsWith 'acme'
target: pipeline
- name: asset-name-must-be-layer-dot-schema-dot-table
description: Asset names must be of the form {layer}.{schema}.{table}
criteria: len(split(asset.Name, '.')) == 3
target: asset # optional
ruleset:
- name: std
rules:
- pipeline-must-have-prefix-acme
- asset-name-must-be-layer-dot-schema-dot-table
```
**Note**
`pipeline` target doesn't work with certain selectors. In particular `asset` …
> Policies: add pipeline level rules

- docs/getting-started/policies.md
- integration-tests/integration-test.go
- integration-tests/policy.yml
- integration-tests/test-pipelines/policies-builtin/assets/alternative.sql
- integration-tests/test-pipelines/policies-builtin/assets/standard.sql
- pkg/lint/policy_builtins.go
- **lint: add builtin rule 'asset-has-primary-key'**
- **lint: policy: add builtin rule for 'column-has-description'**
- **lint: policy: add builtin rule for 'assets-has-checks'**
- **lint: policy: add builtin rule for 'column-has-type'**
- **lint: policy: add builtin rule for 'column-name-is-snake-case'**
- **lint: policy: add builtin rule 'column-name-is-camel-case'**
- **lint: policy: add builtin rule for 'asset-has-tags'**
- **feat: add new rules for column types**
> policies/additional builtin rules/BRU 1918

- cmd/run.go
Running a malformed asset was previously causing a nil pointer error as two functions were trying to access task.Name from a nil pointer.
By adding these checks, the failed asset now returns the following error message:
However if we run the entire pipeline, the asset is ignored for validation (there are actually 39 well-formed assets + 1 mal-formed asset in this pipeline) and the pipeline executes: 
Stopping the pipeline at this point and returning an error message would involve rewriting some of the unit tests.
> Added nil pointer checks in run.go

- integration-tests/integration-test.go
- integration-tests/policy.yml
- integration-tests/test-pipelines/policies-builtin/assets/standard.sql
- integration-tests/test-pipelines/policies-validate-single-asset/assets/target.sql
- integration-tests/test-pipelines/policies-validate-single-asset/pipeline.yml
- pkg/lint/lint.go
- pkg/lint/list.go
- pkg/lint/policy.go
This PR changes how and when policies are loaded.
In the current version of Bruin, policies are loaded during startup once, and then reused during the lifecycle of the application. However, the policy file resolver would always look for a git directory as a proxy for the bruin project. This is error-prone and can break in unexpected ways.
The new version resolves the git directory relative to the target resource (`pipeline`/`asset`) and is more robust. The policy file is loaded only when the `lint.*` family of functions are called. 
This change doesn't utilize file system caching, so it may have a negative impact on lint performance. A future change will address this.
> Policy: resolve config dynamically

- cmd/run.go
- docs/platforms/emr_serverless.md
- pkg/athena/checks.go
- pkg/emr_serverless/checks.go
- pkg/emr_serverless/operator.go
This PR adds support for running quality checks on EMR Serverless assets using AWS Athena. You can now define column and custom checks for your Spark jobs.
**How to enable:**
1. Create an Athena table over your output data.
2. Add an Athena connection in your `bruin.yml`.
3. Set `parameters.athena_connection` in your asset.
**Example asset:**
```yaml
name: users
type: emr_serverless.spark
columns:
- name: id
type: integer
checks:
- non_negative
custom_checks:
- name: users are adults
query: SELECT count(*) from users where age < 18
value: 0
parameters:
athena_connection: athena-default
```
> EMR Serverless: Enable Quality Checks

- cmd/const.go
- internal/requirements.txt
- pkg/lineage/lineage_test.go
- pythonsrc/parser/main.py
- pythonsrc/parser/main_test.py
This PR introduces two changes:
- it removes certain optimizations that are heavy in large queries
- it calculates and reuses a scope in lineage
based on my benchmarks, it improves the basic cases ~30% while allowing 4-5x improvement in some pathological queries.
```
Benchmark 1: before
Time (mean ± σ):      3.630 s ±  0.022 s    [User: 0.054 s, System: 0.017 s]
Range (min … max):    3.604 s …  3.680 s    10 runs
Benchmark 2: after
Time (mean ± σ):     910.2 ms ±   9.8 ms    [User: 52.7 ms, System: 23.7 ms]
Range (min … max):   902.0 ms … 932.8 ms    10 runs
Summary
after ran
3.99 ± 0.05 times faster than before
```
My understanding is that the larger the query, the bigger the difference. There still is a linear growth of the latency though, I couldn't solve that yet.
> patch: improve performance for lineage via prebuilding scope

- pkg/athena/materialization.go
- pkg/clickhouse/materialization_test.go
- pkg/clickhouse/materializer.go
This correction makes sure that the Clickhouse assets using the DDL materialization strategy ignore the full-refresh flag.
DDL materialization should always as be rendered as CREATE TABLE IF NOT EXIST (....) and should not drop the table or be rendered as CREATE OR REPLACE TABLE  (...) etc. 
Added unit test for testing.
> Check for DDL for full refresh in Clickhouse materializer

- integration-tests/test-pipelines/parse-asset-extends/expectations/pipeline.json
- integration-tests/test-pipelines/parse-asset-lineage-pipeline/expectations/lineage.json
- integration-tests/test-pipelines/parse-default-option/expectations/pipeline.yml.json
- integration-tests/test-pipelines/parse-happy-path/expectations/pipeline.yml.json
- integration-tests/test-pipelines/parse-lineage-pipeline/expectations/lineage.json
- integration-tests/test-pipelines/parse-whole-pipeline/expectations/pipeline.yml.json
- pkg/pipeline/pipeline.go
- pkg/pipeline/testdata/pipeline/first-pipeline_unix.json
- pkg/pipeline/testdata/pipeline/first-pipeline_windows.json
- pkg/pipeline/testdata/pipeline/pipeline-with-no-assets_unix.json
- pkg/pipeline/testdata/pipeline/pipeline-with-no-assets_windows.json
- pkg/pipeline/testdata/pipeline/second-pipeline_unix.json
- pkg/pipeline/testdata/pipeline/second-pipeline_windows.json
A `Concurrency` field was added to the `Pipeline` struct in `pkg/pipeline/pipeline.go`.
*   The new field is an `int` type.
*   It includes `json`, `yaml`, and `mapstructure` tags, ensuring proper serialization and deserialization consistent with other struct fields.
*   The field's addition enables specifying the number of concurrent runs for a pipeline, directly addressing the need for controlling execution concurrency, as indicated by the context of enabling "5 concurrent runs" for a specific pipeline.
*   The field was logically placed after the `Retries` field within the struct definition.
> Add concurrency field to Pipeline struct

- pkg/python/uv.go
- pkg/python/uv_test.go
If the users `pyproject.toml` files specifies a version contraint, it may conflict with the version used by bruin.
For example:
```toml
[tool.uv]
required-version=">=0.7.16"
```
would cause bruin to fail with:
<pre>
<span style="color:#33D17A"><b>Executed 1 tasks in 6ms</b></span>
<span style="color:#F66151"><b>Failed assets 1</b></span>
<span style="color:#F66151"><b>.</b></span>
<span style="color:#F66151"><b>└── myschema.country_list</b></span>
<span style="color:#F66151"><b>    └── &apos;failed to execute Python script: failed to check uv version: exit status 2 -- Output: error: Required uv version `&gt;=0.7.16` does not match the running version `0.6.16`</b></span>
<span style="color:#F66151"><b>        &apos;</b></span>
</pre>
> uv: avoid discovering configuration files

- docs/.vitepress/config.mjs
- docs/ingestion/trustpilot.md
- integration-tests/expected_connections_schema.json
- pkg/config/connections.go
- pkg/config/manager.go
- pkg/config/manager_test.go
- pkg/config/testdata/simple.yml
- pkg/config/testdata/simple_win.yml
- pkg/connection/connection.go
- pkg/trustpilot/client.go
- pkg/trustpilot/config.go
Below changes are made in this PR:
- create Trustpilot client and config
- wire Trustpilot connection into connection manager and configuration handling
- document Trustpilot ingestion usage
- add Trustpilot examples to sample config files
- expose Trustpilot docs link in navigation
> Add Trustpilot connection

- cmd/fetch.go
- pkg/sqlparser/parser.go
- pkg/sqlparser/parser_test.go
- pythonsrc/main.py
- pythonsrc/parser/main.py
- pythonsrc/parser/main_test.py
- Only applies limit to single SELECT queries - Multi-statement or non-SELECT queries remain unchanged
- Prevents CLI failures on non-SELECT statements (INSERT, UPDATE, CREATE, etc.)
> handle non select and multiple queries

- cmd/import.go
- main.go
Adds a new command  called **Bruin import** -> Connects to your database, scans tables, and creates .sql asset files with basic SELECT queries in your pipeline's assets/ directory.
1. flags
2. --connection (required): Database connection name
3. --database: Filter by specific database
4. --schema: Filter by specific schema
5. --fill-columns: Include column metadata
6. --environment: Target environment
7. --config-file: Custom config file path
> feat: bruin import

- pkg/tableau/client.go
Tableau refresh endpoints return a **202 Accepted** response, meaning the refresh runs asynchronously. This PR adds logic to track the job status after initiating a refresh to ensure it completes successfully.
> feat add polling for job status

- pkg/tableau/client.go
- pkg/tableau/client_test.go
- pkg/tableau/operator.go
Tableau refresh workloads requires workbook_id or datasource_id  to be set in order to work. Tableau doesnt really provide an easy way to get this ids ( you can get it by their API). This pr extends tableau client so that we can extract these ids by iterating over all of the datasources or workbooks and find the id for the users. 
Following PRs will integrate this into tableau assets so users won't have to provide the ids themselves.
> enrich tableau client

- Makefile
Fixed make test to exclude cloud integration tests as intended.
> fixed makefile to skip cloud-integration-tests

- Makefile
The logs folder was getting filled with thousands of files over time as dozens of tests are run on each integration test run. The make integration-test commands now cleans up the integration-test directory.
> feat: make integration-test-clean command to clean up logs

- integration-tests/cloud-integration-tests/postgres/postgres_test.go
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/scd2-by-column-pipeline/assets/menu.sql
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/scd2-by-time-pipeline/assets/products.sql
Tests now run using a temp directory, which avoids file clean up after running tests.
> Fix: add temp dir to postgres integration tests

- integration-tests/cloud-integration-tests/redshift/redshift_test.go
- integration-tests/cloud-integration-tests/redshift/test-pipelines/scd2-pipelines/scd2-by-time-pipeline/assets/products.sql
- pkg/postgres/materialization.go
- pkg/postgres/materialization_test.go
Fixed Timestamp syntax error for scd2-by-column in redshift.
Updated redshift integration-tests to use temp directory - all passing.
> Fix timestamp and tempdir - redshift

- Makefile
- integration-tests/README.md
`make integration-test-light` was deleted after the refactor. Here I've re-added it to the make file with its old logic of running the integration tests without the ingestr tasks.
> Fix: restore command  "make integration-test-light"

- cmd/init.go
The command bruin init --in-place {template-name} now creates the template in an unitialised repo without creating the bruin parent folder.
> Feature: initialise template in place 

- Makefile
- pkg/e2e/task.go
- pkg/e2e/workflow.go
In a previous PR I deleted the test logs are we were no longer using the for the `make integration-test` command output. They are however still useful when debugging single tests, as you can more clearly see in which step a workflow failed etc. So I re-implemented the comments but added a flag to silence them on running the `make integration-test` command.
> Fix: improve test logging for debugging

- docs/platforms/snowflake.md
- pkg/config/connections.go
Fixed Private Key Injection:
1. Modified `SnowflakeConnection.MarshalJSON()` to read private key content from files automatically. Python assets now receive the actual private key content, not just file paths
2.  Removed `private_key_path` from JSON output sent to Python assets
3. Added Warning for Configuration Conflicts. Shows warning when both `private_key` and `private_key_path` are specified.
Explains which value is being used (direct content takes priority).
4. Updated Documentation
> Fix: snowflake private key

- cmd/internal.go
- cmd/internal_test.go
Add flags environment, start-date and end-date to asset-metadata.
Tested manually.
> Feature: added start and end date to asset-metadata

- .github/workflows/build-test.yml
- .github/workflows/release.yml
- Dockerfile
This pull request updates the Docker build and release workflows and refactors the `Dockerfile` to improve build performance, caching, and image reproducibility. The main changes include switching to multi-stage builds, optimizing Docker layer caching, and passing version information from CI to the build. These updates make the build process more robust and efficient for both CI and local development.
**Dockerfile refactor and build improvements:**
* Refactored `Dockerfile` to use a multi-stage build: compiles the Go application with build arguments for `VERSION` and `BRANCH_NAME`, installs necessary dependencies, and copies the built binary to the final image. Adds a healthcheck for the application.
**CI workflow enhancements:**
* Updated `.github/workflows/build-test.yml` and …
> Fix: docker build
