- examples/simple-pipeline/assets/hello_ingestr7_asset.yml
- examples/simple-pipeline/pipeline.yml
- pkg/config/manager.go
- pkg/config/manager_test.go
- pkg/config/testdata/simple.yml
- pkg/connection/connection.go
- pkg/pipeline/pipeline.go
- pkg/stripe/config.go
- pkg/stripe/db.go
Below changes are made in this PR:
- added  StripeConnection struct and method to return the connection's name.
- added/removed Stripe connection from a specific environment by name
- added stripe option in pipeline.go
- added config and db file to klaviyo package
> Add stripe connection

- examples/simple-pipeline/assets/hello_ingestr9_asset.yml
- examples/simple-pipeline/pipeline.yml
- pkg/config/manager.go
- pkg/config/manager_test.go
- pkg/config/testdata/simple.yml
- pkg/connection/connection.go
- pkg/kafka/config.go
- pkg/kafka/db.go
- pkg/pipeline/pipeline.go
Below changes are made in this PR:
- added Kafka Connection struct and method to return the connection's name.
- added/removed Kafka connection from a specific environment by name
- added Kafka option in pipeline.go
- added config and db file to Kafka package
> Kafka as a new ingestr source

- cmd/helpers.go
- cmd/lint.go
- pkg/connection/connection.go
fix: https://github.com/bruin-data/bruin/issues/96
> Hotfix: handle Panic in connection manager

- cmd/render.go
> added json response for error in render command

- .github/workflows/release.yml
Workflow: https://github.com/y-bruin/bruin/actions/runs/11589375377/job/32265106008
Release: https://github.com/y-bruin/bruin/releases/tag/v0.0.20
> Fix windows release 

- .goreleaser.yaml
- cmd/helpers.go
- go.mod
- go.sum
- pkg/connection/connection.go
- pkg/duckdb/checks.go
- pkg/duckdb/checks_test.go
- pkg/duckdb/db.go
- pkg/duckdb/db_test.go
- pkg/duckdb/materialization_test.go
- pkg/duckdb/operator_test.go
> Revert "disable duckdb on windows"

- docs/getting-started/introduction.md
> Added troubleshooting docs in installation page 

- cmd/init.go
> Revert "git init on bruin init"

- docs/commands/fetch.md
- pkg/snowflake/checks_test.go
- pkg/snowflake/db.go
- pkg/snowflake/db_test.go
- pkg/snowflake/operator.go
added selectWithSchema to snowflake.db and test cases for the function.
>  added snowflake related logic for fetch cmd

- templates/shopify-bigquery/README.md
- templates/shopify-bigquery/assets/shopify.balance.asset.yml
- templates/shopify-bigquery/assets/shopify.customers.asset.yml
- templates/shopify-bigquery/assets/shopify.discounts.asset.yml
- templates/shopify-bigquery/assets/shopify.events.asset.yml
- templates/shopify-bigquery/assets/shopify.inventory_items.asset.yml
- templates/shopify-bigquery/assets/shopify.orders.asset.yml
- templates/shopify-bigquery/assets/shopify.price_rules.asset.yml
- templates/shopify-bigquery/assets/shopify.products.asset.yml
- templates/shopify-bigquery/assets/shopify.transactions.asset.yml
Test
```
Analyzed the pipeline 'bruin-init' with 7 assets.
Pipeline: bruin-init (.)
No issues found
✓ Successfully validated 7 assets across 1 pipeline, all good.
Starting the pipeline execution...
[2024-11-13 15:11:11] Starting: shopify_raw.products
[2024-11-13 15:11:11] Starting: shopify_raw.events
[2024-11-13 15:11:11] Starting: shopify_raw.discounts
[2024-11-13 15:11:11] Starting: shopify_raw.orders
[2024-11-13 15:11:11] Starting: shopify_raw.inventory_items
[2024-11-13 15:11:11] Starting: shopify_raw.customers
[2024-11-13 15:11:11] Starting: shopify_raw.price_rules
[2024-11-13 15:11:12] [shopify_raw.customers] >> 
[2024-11-13 15:11:12] [shopify_raw.customers] >> Initiated the pipeline with the following:
[2024-11-13 15:11:12] [shopify_raw.customers] >>   Source: shopify / customers …
```
> Fix Bigquery template 

- docs/ingestion/shopify.md
- Align shopify docs with other ingestr docs
> Fix shopify docs 

- pkg/duckdb/checks_test.go
- pkg/duckdb/db.go
- pkg/duckdb/db_test.go
- pkg/duckdb/operator.go
>  added duckdb to fetch command

- pkg/pipeline/pipeline.go
Added an error message for hinting users should use asset.yml for ingestr assets
>  added an error message for ingestr assets

- docs/.vitepress/config.mjs
- docs/commands/clean.md
- docs/commands/environments.md
- docs/commands/fetch.md
- docs/commands/format.md
- docs/commands/lineage.md
- docs/commands/render.md
Added documentation for cli commands
> added docs for commands

- pkg/athena/checks_test.go
- pkg/athena/db.go
- pkg/athena/db_test.go
- pkg/athena/operator.go
added athena connection to fetch command
> added athena connection to fetch command

- docs/getting-started/tutorials.md
- pkg/duckdb/db.go
- pkg/duckdb/db_test.go
Fixes small problems regarding to tutorial
>  fixes in tutorial 

- pkg/postgres/checks_test.go
- pkg/postgres/db.go
- pkg/postgres/db_test.go
- pkg/postgres/operator.go
added postgres support for fetch cmd
> added postgres support for fetch cmd

- docs/.vitepress/config.mjs
- docs/commands/validate.md
added validate docs and listes commands in alphabetical order in docs
> added validate docs 

- pkg/bigquery/db.go
- pkg/databricks/db.go
- pkg/databricks/db_test.go
- pkg/postgres/checks_test.go
- pkg/postgres/db.go
- pkg/postgres/db_test.go
- pkg/postgres/operator.go
added postgres connection to testing cmd  and fixed some naming conventions
>  added postgres test connection and some fixes

- templates/duckdb-lineage/.bruin.yml
- templates/duckdb-lineage/README.md
- templates/duckdb-lineage/assets/country.sql
- templates/duckdb-lineage/assets/example.sql
- templates/duckdb-lineage/assets/people.sql
- templates/duckdb-lineage/assets/users.sql
- templates/duckdb-lineage/pipeline.yml
Test
```
$ bruin internal parse-pipeline -c  templates/duckdb-lineage/
$ bruin internal parse-asset -c  templates/duckdb-lineage/assets/example.sql
```
> Added template for duckdb lineage example

- pkg/pipeline/lineage.go
Test Case: https://github.com/y-bruin/bruin-dev/blob/main/duckdb/assets/country.sql
Output: http://jsonblob.com/1310545255808032768
> Fix sql function parsing in column lineage

- cmd/docs.go
- main.go
`bruin docs --open` to open the docs  `bruin docs` to get the link of the docs
>  added docs command

- cmd/run.go
- pkg/pipeline/pipeline.go
- pkg/scheduler/scheduler.go
> Fix metadata push

- integration-tests/lineage/assets/country.sql
- integration-tests/lineage/assets/people.sql
- integration-tests/lineage/expectations/lineage-asset.json
- integration-tests/lineage/expectations/lineage.json
- pkg/pipeline/lineage.go
- pkg/sqlparser/parser.go
Context: https://github.com/bruin-data/bruin/pull/292
> Added non selected columns in lineage package

- cmd/const.go
- cmd/internal.go
- cmd/lineage.go
- cmd/lint.go
- cmd/render.go
- cmd/run.go
- pkg/lint/lint.go
- pkg/lint/lint_test.go
- pkg/path/walk.go
- pkg/path/walk_test.go
- pkg/pipeline/pipeline.go
- pkg/pipeline/pipeline_test.go
refactored Pipelinedefinition file to support pipeline.yaml files as well as all related functions to it
>  add pipeline.yaml support

- cmd/internal.go
- pkg/pipeline/lineage.go
- pkg/pipeline/lineage_test.go
- Updated `TableSchema` method to return column metadata instead of maintaining the state.
- Modified `ColumnLineage` method to accept metadata as a parameter, enhancing lineage analysis.
- Adjusted related parsing functions to utilize the new metadata structure, ensuring consistent lineage extraction across the codebase.
> Refactor lineage table schema extraction

- docs/public/getting-started/introduction.html
added redirect from old introduction link
> add redirect from old link

- pkg/athena/materialization.go
- pkg/athena/materialization_test.go
- pkg/bigquery/materialization.go
- pkg/bigquery/materialization_test.go
- pkg/databricks/materialization.go
- pkg/databricks/materialization_test.go
- pkg/duckdb/materialization.go
- pkg/duckdb/materialization_test.go
- pkg/mssql/materialization.go
- pkg/mssql/materialization_test.go
- pkg/postgres/materialization.go
- pkg/postgres/materialization_test.go
- pkg/snowflake/materialization.go
- pkg/snowflake/materialization_test.go
semicolon gets commented out if there is a comment at the end of the query
> fix:Materialization Comment Out Problem

- pkg/config/manager.go
- pkg/config/manager_test.go
- pkg/config/testdata/simple_win.yml
now you can do` cd some-pipeline ` and still give a relative path to your service account file
> abs path for gcp

- .github/workflows/build-test.yml
- cmd/internal_test.go
- cmd/lint_test.go
Added Unit Tests for Benchmarking `validate`, `internal parse-pipeline` and `internal parse-asset` command
> Added Unit Tests for Benchmarking 

- .golangci.yml
- docs/.vitepress/config.mjs
- docs/ingestion/asana.md
- examples/simple-pipeline/pipeline.yml
- integration-tests/expected_connections_schema.json
- pkg/asana/client.go
- pkg/asana/config.go
- pkg/config/connections.go
- pkg/config/manager.go
- pkg/config/manager_test.go
- pkg/config/testdata/simple.yml
- pkg/config/testdata/simple_win.yml
- pkg/connection/connection.go
- pkg/pipeline/pipeline.go
- pkg/python/uv.go
**Configuration**
To use Asana asset, the connection configuration will look like the following:
```yaml
environments:
default:
connections:
asana:
- name: "my-asana"
workspace: "YOUR_WORKSPACE_ID"
access_token: "YOUR_ACCESS_TOKEN"
```
> Integrate Asana Ingestr Source

- docs/.vitepress/config.mjs
- docs/ingestion/dynamodb.md
- examples/simple-pipeline/pipeline.yml
- integration-tests/expected_connections_schema.json
- pkg/config/connections.go
- pkg/config/manager.go
- pkg/config/manager_test.go
- pkg/config/testdata/simple.yml
- pkg/config/testdata/simple_win.yml
- pkg/connection/connection.go
- pkg/dynamodb/client.go
- pkg/dynamodb/config.go
- pkg/pipeline/pipeline.go
**Configuration**
To use DynamoDB Ingestr asset, the connection configuration will look like the following:
```yaml
environments:
default:
connections:
dynamodb:
- name: "my-dynamodb"
access_key_id: "AWS_ACCESS_KEY_ID"
secret_access_key: "AWS_SECRET_ACCESS_KEY"
region: "AWS_REGION"
```
> Integrate DynamoDB source

- cmd/helpers.go
- cmd/lint.go
- cmd/run.go
- pkg/scheduler/scheduler.go
- Refactor switchEnvironment function to accept parameters directly and update calls in Lint and Run commands.  
- Introduce ConfigureLogs function for log file setup in Run command, improve code organization and readability.
> Refactor run command to reuse all flags from the state 

- Makefile
- integration-tests/.bruin.yml
- integration-tests/expected_connections.json
- integration-tests/integration-test.go
- integration-tests/test-pipelines/ingestr-pipeline/assets/chess_games.asset.yml
- integration-tests/test-pipelines/ingestr-pipeline/assets/chess_profiles.asset.yml
- integration-tests/test-pipelines/ingestr-pipeline/assets/player_summary.sql
- integration-tests/test-pipelines/ingestr-pipeline/pipeline.yml
integration-test  runs on ci and it includes ingestr tasks
integration-test-light you can run this on your local without ingestr tasks for fast execution
> add integration test light

- pkg/snowflake/checks_test.go
- pkg/snowflake/db.go
- pkg/snowflake/operator.go
- pkg/snowflake/operator_test.go
if user has new_database.table in  a snowflake asset which doesn't exists, create the database
> handle new databases in snowflake 

- pkg/snowflake/checks_test.go
- pkg/snowflake/db.go
- pkg/snowflake/operator.go
- pkg/snowflake/operator_test.go
added :  user can change the materialization type after the table is already created
> Snowflake  handle materialization type  changes

- docs/.vitepress/config.mjs
- docs/ingestion/appstore.md
- integration-tests/expected_connections_schema.json
- pkg/appstore/client.go
- pkg/appstore/config.go
- pkg/config/connections.go
- pkg/config/manager.go
- pkg/config/manager_test.go
- pkg/config/testdata/simple.yml
- pkg/config/testdata/simple_win.yml
- pkg/connection/connection.go
- pkg/pipeline/pipeline.go
- pkg/python/uv.go
Sample configuration:
```yaml
default_environment: default
environments:
default:
connections:
appstore:
- name: "appstore-default"
key_id: "<redacted>"
issuer_id: "<redacted>"
key_base64: "<private key base64>"
duckdb:
- name: "duckdb-default"
path: "/home/user/test-appstore-bruin/appstore.db"
```
```yaml
name: public.downloads
type: ingestr
parameters:
source_connection: appstore-default
source_table: "app-downloads-detailed:12345678"
destination: duckdb
```
> Add AppStore source

- pkg/lint/list.go
- pkg/lint/rules.go
- pkg/lint/rules_test.go
- pkg/python/uv.go
Changes: 
- Added validation rule for python asset
> Patch: Python matrialization

- cmd/fetch.go
- cmd/fetch_test.go
- pkg/mssql/db.go
added tests ,
changed flag validation, 
changed query limiting strategy
> Query  command refactoring 

- go.mod
- go.sum
- package-lock.json
- package.json
Upgrade vite, vitepress, esbuild, and Go module (go-jose) to latest stable versions
> dependabot updates 

- cmd/internal.go
- pkg/lineage/lineage.go
- pkg/lineage/lineage_test.go
- pkg/pipeline/pipeline.go
- Move lineage code to separate package because of Circular dependency
- Return LineageError from lineage package that have all the errors related to pipeline
- Ignore Error in Bruin CLI
> feat: Implement column lineage parsing and error handling in Go

- cmd/run.go
Changes:
- Add environment variable support for start and end dates 
- Add environment variable support for full refresh
> Add environment variable support for start and end dates 

- integration-tests/.bruin.yml
- integration-tests/expected_connections.json
- integration-tests/integration-test.go
- integration-tests/test-pipelines/run-non-wait-symbolic/assets/asset1.sql
- integration-tests/test-pipelines/run-non-wait-symbolic/assets/asset2.sql
- integration-tests/test-pipelines/run-non-wait-symbolic/assets/example.sql
- integration-tests/test-pipelines/run-non-wait-symbolic/assets/my-other-asset.sql
- integration-tests/test-pipelines/run-non-wait-symbolic/pipeline.yml
- pkg/pipeline/yaml.go
- pkg/scheduler/scheduler.go
Changes:
- Fix parsing of depends 
- feat:  non-wait / symbolic dependency
- integration test for  non-wait / symbolic dependency
> feat: non-wait / symbolic dependency

- cmd/fetch.go
- pkg/lint/list.go
- pkg/lint/rules.go
- pkg/lint/rules_test.go
This PR adds a new validation rule to catch plain YAML files that the user might have intended as assets. Bruin expects assets to be defined as `<name>.asset.yml`.
> add a new linter rule for yaml assetS

- examples/simple-pipeline/assets/hello_ingestr15_asset.yml
- examples/simple-pipeline/pipeline.yml
- integration-tests/expected_connections_schema.json
- pkg/config/connections.go
- pkg/config/manager.go
- pkg/config/manager_test.go
- pkg/config/testdata/simple.yml
- pkg/config/testdata/simple_win.yml
- pkg/connection/connection.go
- pkg/googleanalytics/client.go
- pkg/googleanalytics/config.go
- pkg/pipeline/pipeline.go
> add google analytics

- docs/ingestion/frankfurter.md
- templates/frankfurter/README.md
Added README to template. Updated frankfurter.md.
> Added README doc to Template

- docs/getting-started/introduction/quickstart.md
| Before | After |
|--------|--------|
| <img width="1119" alt="image" src="https://github.com/user-attachments/assets/69b407be-9437-4e47-b33d-ce306c392123" /> | <img width="1119" alt="image" src="https://github.com/user-attachments/assets/97ead474-0205-46bf-8ae3-0027f813a18d" /> |
> Update quickstart.md to fix rendering issue in the VS Code extension

- Makefile
- pkg/duckdb/db.go
- pkg/duckdb/db_no_duckdb.go
- pkg/duckdb/ephemeral_db.go
- pkg/duckdb/ephemeral_db_no_duckdb.go
Cursor implemented this in one shot really.
> add a new tag for a build without duckdb

- docs/ingestion/spanner.md
- integration-tests/expected_connections_schema.json
- pkg/config/manager.go
- pkg/config/testdata/simple.yml
- pkg/config/testdata/simple_win.yml
> rename 'gcp_spanner' yaml/json field to 'spanner' and adjust test data

- docs/getting-started/tutorials/template-tutorial.md
I fixed the embedded youtube link in tutorials/template-tutorial.md.
> Fixed Embedded Youtube Link

- cmd/helpers.go
- cmd/init.go
- cmd/run.go
> Non zero status on panic

- cmd/environments.go
- cmd/environments_test.go
- cmd/testdata/test-config.yml
- pkg/config/manager.go
bruin environments update --name dev --new-name development
--schema-prefix "dev_"
bruin environments delete --name staging
bruin environments delete --name staging --force
bruin environments update --name dev --new-name development
--output json
All commands integrate seamlessly with existing CLI patterns
and include comprehensive error handling.
> Add Environments Delete , Update 

- integration-tests/cloud-integration-tests/postgres/postgres_test.go
- integration-tests/cloud-integration-tests/postgres/test-pipelines/asset-query-pipeline/assets/products_individual.sql
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/resources/menu_original.sql
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/resources/menu_updated_01.sql
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/resources/menu_updated_02.sql
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/resources/products_original.sql
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/resources/products_updated_01.sql
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/resources/products_updated_02.sql
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/scd2-by-column-pipeline/assets/menu.sql
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/scd2-by-column-pipeline/expectations/scd2_by_col_expected_initial.csv
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/scd2-by-column-pipeline/expectations/scd2_by_col_expected_updated_01.csv
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/scd2-by-column-pipeline/expectations/scd2_by_col_expected_updated_02.csv
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/scd2-by-column-pipeline/pipeline.yml
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/scd2-by-time-pipeline/assets/products.sql
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/scd2-by-time-pipeline/expectations/scd2_by_time_expected_initial.csv
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/scd2-by-time-pipeline/expectations/scd2_by_time_expected_update_01.csv
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/scd2-by-time-pipeline/expectations/scd2_by_time_expected_update_02.csv
- integration-tests/cloud-integration-tests/postgres/test-pipelines/scd2-pipelines/scd2-by-time-pipeline/pipeline.yml
- pkg/postgres/materialization.go
- pkg/postgres/materialization_test.go
Added SCD2_by_col and SCD2_by_time to postgres.
Added unit tested for materialization.
Added integration tests.
> added SCD2_by_col and SCD2_by_time to postgres

- docs/ingestion/gcs.md
- integration-tests/expected_connections_schema.json
- pkg/config/connections.go
- pkg/config/manager_test.go
- pkg/config/testdata/simple.yml
- pkg/config/testdata/simple_win.yml
- pkg/connection/connection.go
- pkg/gcs/config.go
> Update GCS connection to be used as destination

- pkg/mssql/db.go
- pkg/mssql/db_test.go
- pkg/mssql/materialization.go
this pr adds support for query and connections test commands for mssql
> Mssql fetch and test

- integration-tests/cloud-integration-tests/athena/athena_test.go
- integration-tests/cloud-integration-tests/athena/test-pipelines/asset-query-pipeline/assets/products_individual.sql
- integration-tests/cloud-integration-tests/athena/test-pipelines/asset-query-pipeline/assets/workflow_test_products.sql
- integration-tests/cloud-integration-tests/athena/test-pipelines/asset-query-pipeline/expected.json
- integration-tests/cloud-integration-tests/athena/test-pipelines/asset-query-pipeline/expected_products_table.csv
- integration-tests/cloud-integration-tests/athena/test-pipelines/asset-query-pipeline/pipeline.yml
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/resources/menu_original.sql
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/resources/menu_updated_01.sql
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/resources/menu_updated_02.sql
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/resources/products_original.sql
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/resources/products_updated_01.sql
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/resources/products_updated_02.sql
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/scd2-by-column-pipeline/assets/menu.sql
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/scd2-by-column-pipeline/expectations/scd2_by_col_expected_initial.csv
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/scd2-by-column-pipeline/expectations/scd2_by_col_expected_updated_01.csv
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/scd2-by-column-pipeline/expectations/scd2_by_col_expected_updated_02.csv
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/scd2-by-column-pipeline/pipeline.yml
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/scd2-by-time-pipeline/assets/products.sql
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/scd2-by-time-pipeline/expectations/scd2_by_time_expected_initial.csv
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/scd2-by-time-pipeline/expectations/scd2_by_time_expected_update_01.csv
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/scd2-by-time-pipeline/expectations/scd2_by_time_expected_update_02.csv
- integration-tests/cloud-integration-tests/athena/test-pipelines/scd2-pipelines/scd2-by-time-pipeline/pipeline.yml
- integration-tests/cloud-integration-tests/cloud-integration_test.go
- pkg/athena/materialization.go
- pkg/athena/materialization_test.go
Added SCD2 by column and by time to Athena.
Added unit tests.
Added integration tests.
> Added scd2-by-col and scd2-by-time for athena 

- .github/workflows/update-ingestr.yml
This PR schedules a github action job that checks for new ingestr versions and updates the code to that version automatically.
> chore: automate ingestr update script

- .github/workflows/release.yml
- Dockerfile
- docs/getting-started/introduction/installation.md
> use cleaner install url

- pkg/s3/operator.go
when using s3 sensors check if the user has an aws connection , then fallback to s3 connection if they dont have that
> support s3 connection

- pkg/postgres/db.go
- pkg/postgres/db_test.go
This PR introduces a more effective method for validating Postgres queries. The previous method relied on `EXPLAIN` queries, which do not work with queries like `TRUNCATE`, this fixes that.
> use test queries instead of select in postgres
